version: "4.2.0"
services:

  api-gateway-service:
    build:
      dockerfile: Dockerfile
      context: ./api-gateway-service
    image: gitlab.lrz.de:5005/ase23-starnberger-serr/onlineide/api-gateway:latest
    restart: on-failure
    #ports:
    #  - 8081:8081
    #depends_on:
    #  - api-gateway-service

  compiler-service:
    build:
      dockerfile: Dockerfile
      context: ./compiler-service
    image: gitlab.lrz.de:5005/ase23-starnberger-serr/onlineide/compiler:latest
    restart: on-failure
    ports:
      - 8081:8081
    depends_on:
      - api-gateway-service

  dark-mode-service:
    build:
      dockerfile: Dockerfile
      context: ./dark-mode-service
    image: gitlab.lrz.de:5005/ase23-starnberger-serr/onlineide/dark-mode:latest
    restart: on-failure
    ports:
      - 8084:8084
    depends_on:
      - api-gateway-service

  project-service:
    build:
      dockerfile: Dockerfile
      context: ./project-service
    image: gitlab.lrz.de:5005/ase23-starnberger-serr/onlineide/project:latest
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      - api-gateway-service
      - db

  service-registry-service:
    build:
      dockerfile: Dockerfile
      context: ./service-registry-service
    image: gitlab.lrz.de:5005/ase23-starnberger-serr/onlineide/service-registry:latest
    restart: on-failure
    ports:
      - 8761:8761
    depends_on:
      - api-gateway-service

  ui-service:
    build:
      dockerfile: Dockerfile
      context: ./ui-service
    image: gitlab.lrz.de:5005/ase23-starnberger-serr/onlineide/ui:latest
    restart: on-failure
    ports:
      - 4200:4200
    depends_on:
      - api-gateway-service
    
  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=project_db
      - POSTGRES_PASSWORD=project_pw
      - POSTGRES_USER=project_user
