spring:
  application:
    name: project-prod-service
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/my_db}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:test}
#server:
#  port: ${PORT:8081}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
